enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@react-spring/animated@*":
    peerDependencies:
      "react": "*"
  "@react-spring/core@*":
    peerDependencies:
      "react": "*"
  "next@*":
    peerDependencies:
      "styled-jsx-plugin-postcss": "*"
  "troika-three-text@*":
    peerDependencies:
      "three": "*"

pnpMode: strict

preferInteractive: true

yarnPath: .yarn/releases/yarn-berry.cjs
